name: MoonGenerator
version: ${project.version}
main: me.shoko.moongenerator.MoonGenerator
api-version: 1.13
depend: [WorldGuard]
authors: [Shoko, Zethrus]
description: Moon world plugin for Miners Glory, fork of great moon generator by Shoko
website: https://minersglory.com
